### ISSUE TITLE
Importing Wallet (NANO)

### ISSUE THREAD

**Issue by Microove** [NemProject/NanoWallet#297]
Trying to import wallet from a USB (coming from Windows) to Macbook Pro.

Tried to launch file locally, didn't work. Doesn't show up in list.

Error given from console:

ascalprecht.translate.$translateSanitization: No sanitization strategy has been configured. This can have serious security implications. See http://angular-translate.github.io/docs/#/guide/19_security for details.
main.js:102027 Loading wallet
main.js:31081 Error: Malformed UTF-8 data
    at Error (native)
    at Object.m.Utf8.stringify (chrome-extension://apgagcmokepionlmmeonmgkemlhdokab/vendors/cryptoJS/core-min.js:10:431)
    at Object.l.WordArray.f.extend.toString (chrome-extension://apgagcmokepionlmmeonmgkemlhdokab/vendors/cryptoJS/core-min.js:8:130)
    at LoginCtrl.loadWallet (chrome-extension://apgagcmokepionlmmeonmgkemlhdokab/main.js:113006:49)
    at fn (eval at <anonymous> (chrome-extension://apgagcmokepionlmmeonmgkemlhdokab/main.js:31916:15), <anonymous>:4:354)
    at chrome-extension://apgagcmokepionlmmeonmgkemlhdokab/main.js:102018:33
    at Scope.$eval (chrome-extension://apgagcmokepionlmmeonmgkemlhdokab/main.js:34736:28)
    at Scope.$apply (chrome-extension://apgagcmokepionlmmeonmgkemlhdokab/main.js:34836:25)
    at FileReader.<anonymous> (chrome-extension://apgagcmokepionlmmeonmgkemlhdokab/main.js:102017:35)

Using macbook pro:
<img width="631" alt="schermafbeelding 2017-09-23 om 14 39 12" src="https://user-images.githubusercontent.com/12142426/30773380-b5136f2e-a06f-11e7-9003-8eaf0dc13c78.png">
<img width="255" alt="schermafbeelding 2017-09-23 om 14 58 28" src="https://user-images.githubusercontent.com/12142426/30773381-b5166a1c-a06f-11e7-9a4e-28114cddd402.png">

**Comment by mizunashi** [comment]
My Windows10 & macOS Sierra 10.12.6 are noproblem.
Is this a occasional bug in CryptJS?

**Comment by Microove** [comment]
Windows 7, it just keeps happening, also with other wallets that I try to import.

All the best,

Michael








VLOW Minded Productions / TWSTd
Verversstraat 2 A+B
1011 JA Amsterdam

E:  michael@vlow-productions.com
M:  (+31)6 58 908 691
T:   (+31)20 772 91 30
S:  'Michael Verhaaf' / 'Microove'
W:  www.vlow-productions.com / www.microove.com

KNOWN AS: 
MICROOVE / ALBĪNO / NOAH / VERSA VICA / SOURCE WITHIN / JUSTIN CASE / WE THE PEOPLE

BOOKED ARTISTS: 
| JOSH WINK [US] | TODD TERRY [US] | KEN ISHII [JP] | ROBERT OWENS [US] | DJ DEEON [US]
| ELBEE BAD [US] | THE JAYDES (BLOODY MARY & ATTAN) [FR/GER] | JONAS KOPP [AR] 
| SHIFTED [UK] | K209 (HENNING BAER & MILTON BRADLEY) [GER] | VAKULA [UA] | CTRLS [DK] 
| TR-101 (SLEEPARCHIVE & DJ PETE) [GER] | AGARIC AKA PATRICK SKOOG [SE] | ANONYM [US] 
| DJ T. [GER] | DJ DEEON [US] | BORIS WERNER | BENNY RODRIGUES | DE SLUWE VOS 
| MAKAM | SANDRIEN | FERRO | JOB JOBSE | LAUHAUS | SAMUEL DEEP | WOUTER DE MOOR 
| TOM RUIJG | MALBETRIEB | THOMAS MARTOJO | CASPER TIELROOIJ | MELON | DISPAR VULGO 
| CAMIEL DAAMEN | KERK! | CARLOS VALDES | ANIL ARAS | BRAM FIDDER | PRUNK | ANIL ARAS 
| DU CHATINIER | REISS | ALEXANDER VALENTYN | JOHANNA MERCKER | GUY GRAVIER 
| MICHIEL TETTERO | MICROOVE AKA NOAH | & MANY MORE

EVENTS:
VLOW | 11:11 FESTIVAL | 22:22 | BELTANE | ALTER EGO | .RICA! | TWSTd | LOCKED | KRUISBESTUIVING 
MONUMENTALL & A LOT OF COLLABORATIONS AND UNDERGROUND EVENTS

VENUES: 
PARADISO / A'DAM TOREN / AIR AMSTERDAM / STUDIO 80 / RUIGOORD | WESTERUNIE / 
CHICAGO SOCIAL CLUB / SUGAR FACTORY / ODEON / CLUB UP / HEM-KELDER / DOK 

The information contained in this communication is confidential, may be privileged 
and is intended for the exclusive use of the above named addressee(s).  If you are 
not the intended recipient(s), you are expressly prohibited from copying, distributing, 
disseminating, or in any other way using any information contained within this 
communication.  We have taken precautions to minimize the risk of transmitting 
software viruses, but we advise you to carry out your own virus checks on any 
attachment to this message.  We cannot accept liability for any loss or damage 
caused by software viruses.  If you have received this communication in error please
contact the sender by telephone or by response via mail.  This communication is from 
V.M.P., registered in Amsterdam, the Netherlands.

Violation of this note may be unlawful.

**Comment by Microove** [comment]
Hi,

I see when I’m in Finder, that the file has a preview picture that says exec, but the new wallet I made with NANO
doesn’t.

Does this help you solve the problem? It comes from Windows 7 btw.

**Comment by QuantumMechanics** [comment]
Hi,

> main.js:31081 Error: Malformed UTF-8 data

This means the data inside the wallet file cannot be read properly.

Is it a NCC wallet ?

**Comment by Microove** [comment]
No, it wasn’t NCC, but NANO. I’ve downloaded the wallets again from the updated Nano wallet
and then it worked.

In the attachment you will find the working wallet (with ‘(2)’ behind it and the one that didn’t work.



This is my adress: NAYD2I-4R6PSU-4I4DKL-CPDEFT-7XLFKF-2NP7UB-CTJM

**Comment by Microove** [comment]
You still here Quantum
