### ISSUE TITLE
Universal Client start.html is blank in Chrome

### ISSUE THREAD

**Issue by ghost** [NemProject/NanoWallet#562]
Before submitting your issue, please review the following checklist:

- [ ] **AVOID** using the issue tracker for questions or help. Submitting issues to this repository are usually reserved for bugs, feature requests, or changes to the source code. If you need help https://forum.nem.io should be first place to visit.
- [ ] **DO** describe operating system and browser used

Debian GNU/Linux 9.5 (stretch)
Chromium Version 69.0.3497.92

## Expected Behavior

A wallet... Or Instructions/Troubleshooting 
## Current Behavior

Just a blank page

## Possible Solution

Or Instructions/Troubleshooting 

## Steps to Reproduce

1. Download https://github.com/NemProject/NanoWallet/releases/download/2.3.2/NanoWallet-2.3.2.zip
2. Unzip..
3. Open ..Downloads/NanoWallet-2.3.2/start.html in browser

## Details

Some more info might make it usable I guess

Looks like a known issue.
https://forum.nem.io/t/universal-client-start-html-is-blank-in-chrome/13183/6

**Comment by kekkyojin** [comment]
EDIT: This is also on the forum for NEM. Sorry. I created this comment before visiting that link. But maybe having this information here could help the problem be fixed, as forums could remove accidentally posts.

Exception code from Brave console log:

main.js:28369 Uncaught Error: [$injector:modulerr] Failed to instantiate module app due to:
Error: Failed to read the 'localStorage' property from 'Window': Access is denied for this document.
    at Object.get (file:///Users/javi/NEM-Wallet-2.4.2/main.js:244005:39)
    at AppConfig (file:///Users/javi/NEM-Wallet-2.4.2/main.js:294673:64)
    at Object.invoke (file:///Users/javi/NEM-Wallet-2.4.2/main.js:33163:19)
    at runInvokeQueue (file:///Users/javi/NEM-Wallet-2.4.2/main.js:33051:35)
    at file:///Users/javi/NEM-Wallet-2.4.2/main.js:33060:11
    at forEach (file:///Users/javi/NEM-Wallet-2.4.2/main.js:28658:20)
    at loadModules (file:///Users/javi/NEM-Wallet-2.4.2/main.js:33041:5)
    at createInjector (file:///Users/javi/NEM-Wallet-2.4.2/main.js:32963:19)
    at doBootstrap (file:///Users/javi/NEM-Wallet-2.4.2/main.js:30143:20)
    at Object.bootstrap (file:///Users/javi/NEM-Wallet-2.4.2/main.js:30164:12)
http://errors.angularjs.org/1.6.2/$injector/modulerr?p0=app&p1=Error%3A%20Failed%20to%20read%20the%20'localStorage'%20property%20from%20'Window'%3A%20Access%20is%20denied%20for%20this%20document.%0A%20%20%20%20at%20Object.get%20(file%3A%2F%2F%2FUsers%2Fjavi%2FNEM-Wallet-2.4.2%2Fmain.js%3A244005%3A39)%0A%20%20%20%20at%20AppConfig%20(file%3A%2F%2F%2FUsers%2Fjavi%2FNEM-Wallet-2.4.2%2Fmain.js%3A294673%3A64)%0A%20%20%20%20at%20Object.invoke%20(file%3A%2F%2F%2FUsers%2Fjavi%2FNEM-Wallet-2.4.2%2Fmain.js%3A33163%3A19)%0A%20%20%20%20at%20runInvokeQueue%20(file%3A%2F%2F%2FUsers%2Fjavi%2FNEM-Wallet-2.4.2%2Fmain.js%3A33051%3A35)%0A%20%20%20%20at%20file%3A%2F%2F%2FUsers%2Fjavi%2FNEM-Wallet-2.4.2%2Fmain.js%3A33060%3A11%0A%20%20%20%20at%20forEach%20(file%3A%2F%2F%2FUsers%2Fjavi%2FNEM-Wallet-2.4.2%2Fmain.js%3A28658%3A20)%0A%20%20%20%20at%20loadModules%20(file%3A%2F%2F%2FUsers%2Fjavi%2FNEM-Wallet-2.4.2%2Fmain.js%3A33041%3A5)%0A%20%20%20%20at%20createInjector%20(file%3A%2F%2F%2FUsers%2Fjavi%2FNEM-Wallet-2.4.2%2Fmain.js%3A32963%3A19)%0A%20%20%20%20at%20doBootstrap%20(file%3A%2F%2F%2FUsers%2Fjavi%2FNEM-Wallet-2.4.2%2Fmain.js%3A30143%3A20)%0A%20%20%20%20at%20Object.bootstrap%20(file%3A%2F%2F%2FUsers%2Fjavi%2FNEM-Wallet-2.4.2%2Fmain.js%3A30164%3A12)
    at file:///Users/javi/NEM-Wallet-2.4.2/main.js:28369:12
    at file:///Users/javi/NEM-Wallet-2.4.2/main.js:33080:15
    at forEach (file:///Users/javi/NEM-Wallet-2.4.2/main.js:28658:20)
    at loadModules (file:///Users/javi/NEM-Wallet-2.4.2/main.js:33041:5)
    at createInjector (file:///Users/javi/NEM-Wallet-2.4.2/main.js:32963:19)
    at doBootstrap (file:///Users/javi/NEM-Wallet-2.4.2/main.js:30143:20)
    at Object.bootstrap (file:///Users/javi/NEM-Wallet-2.4.2/main.js:30164:12)
    at Object.2163../components (file:///Users/javi/NEM-Wallet-2.4.2/main.js:293322:19)
    at o (file:///Users/javi/NEM-Wallet-2.4.2/main.js:1:265)
    at r (file:///Users/javi/NEM-Wallet-2.4.2/main.js:1:431)
(anonymous) @ main.js:28369
(anonymous) @ main.js:33080
forEach @ main.js:28658
loadModules @ main.js:33041
createInjector @ main.js:32963
doBootstrap @ main.js:30143
bootstrap @ main.js:30164
2163../components @ main.js:293322
o @ main.js:1
r @ main.js:1
(anonymous) @ main.js:1

Taken when running 2.4.2 and 2.4.4 on Dissenter browser (Brave/Chromium fork). The same version is working as expected on Firefox 67 macOS

**Comment by kekkyojin** [comment]
However it is working in Vivaldi 2.5, also a Chromium fork.
